name: API tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn add global newman && yarn add global newman-reporter-html

      - name: Run API tests
        run: yarn test:api --env-var "auth_token=${{ secrets.AUTH_TOKEN }}"

      - name: Upload Newman HTML report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports
          path: reports/
          retention-days: 7